# Generated by Django 5.2.8 on 2025-11-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(blank=True, default='Zazzle_Nature_Love_Modern_Invitation__Front_Back_-removebg-preview.png', upload_to=''),
        ),
    ]
